#!/usr/bin/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/zabbix
source /assets/defaults/zabbix-server
PROCESS_NAME="zabbix-server"

check_container_initialized
liftoff

print_start "Starting Zabbix Server ${ZABBIX_VERSION}"
silent s6-setuidgid ${ZABBIX_USER} zabbix_server -c "${ZABBIX_SERVER_CONFIG_PATH}"/"${ZABBIX_SERVER_CONFIG_FILE}" -f;
