#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="zabbix-proxy"

### Debug Mode
if var_true "$DEBUG_MODE"; then
  ZABBIX_PROXY_DEBUG_LEVEL=4
fi

### Check to see if Enabled/Disabled
if var_true $ENABLE_ZABBIX; then
  sed -i -e "s|<ZABBIX_PROXY_LOGTYPE>|$ZABBIX_PROXY_LOGTYPE|g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s|<ZABBIX_PROXY_LOGFILE>|$ZABBIX_PROXY_LOGFILE|g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_LOGFILESIZE>/$ZABBIX_PROXY_LOGFILESIZE/g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_DEBUG_LEVEL>/$ZABBIX_PROXY_DEBUG_LEVEL/g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_MODE>/$ZABBIX_PROXY_MODE/g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_REMOTECOMMANDS>/$ZABBIX_PROXY_REMOTECOMMANDS/g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_REMOTECOMMANDS_LOG>/$ZABBIX_PROXY_REMOTECOMMANDS_LOG/g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s|<ZABBIX_PROXY_SERVER>|$ZABBIX_PROXY_SERVER|g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_LISTEN_PORT>/$ZABBIX_PROXY_LISTEN_PORT/g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_SERVER_PORT>/$ZABBIX_PROXY_SERVER_PORT/g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_HOSTNAME>/$ZABBIX_PROXY_HOSTNAME/g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_ALLOW_ROOT>/$ZABBIX_PROXY_ALLOW_ROOT/g" /etc/zabbix/zabbix_proxy.conf
  sed -i -e "s/<ZABBIX_PROXY_USER>/"$ZABBIX_PROXY_USER"/g" /etc/zabbix/zabbix_proxy.conf

  mkdir -p /var/log/zabbix
  chown -R "$ZABBIX_PROXY_USER" /var/log/zabbix
  chown -R "$ZABBIX_PROXY_USER" /etc/zabbix/

  if [ -d /assets/externalscripts ]; then
    cp -R /assets/externalscripts/* /usr/lib/zabbix/externalscripts
    chown -R "$ZABBIX_PROXY_USER" /usr/lib/zabbix/externalscripts
    chmod -R 0755 /usr/lib/zabbix/externalscripts
  fi

  if [ -d /assets/alertscripts ]; then
    cp -R /assets/alertscripts/* /usr/lib/zabbix/alertscripts
    chown -R "$ZABBIX_PROXY_USER" /usr/lib/zabbix/alertscripts
    chmod -R 0755 /usr/lib/zabbix/alertscripts
  fi

else
  print_debug "Disabling Zabbix Proxy"
  service_stop 10-zabbix-proxy
fi

liftoff
