#!/usr/bin/with-contenv bash

### Set Defaults
  ENABLE_ZABBIX_PROXY=${ENABLE_ZABBIX_PROXY:-"TRUE"}
  ZABBIX_PROXY_LOGTYPE=${ZABBIX_PROXY_LOGTYPE:-"console"}
  ZABBIX_PROXY_LOGFILE=${ZABBIX_PROXY_LOGFILE:-"/var/log/zabbix/zabbix_proxy.log"}
  ZABBIX_PROXY_LOGFILESIZE=${ZABBIX_PROXY_LOGFILESIZE:-"1"}
  ZABBIX_PROXY_MODE=${ZABBIX_PROXY_MODE:-"0"}

  ZABBIX_PROXY_DEBUG_LEVEL=${ZABBIX_PROXY_DEBUG_LEVEL:-"2"}
  ZABBIX_PROXY_REMOTECOMMANDS=${ZABBIX_PROXY_REMOTECOMMANDS:-"1"}
  ZABBIX_PROXY_REMOTECOMMANDS_LOG=${ZABBIX_PROXY_REMOTECOMMANDS_LOG:-"1"}
  ZABBIX_PROXY_SERVER=${ZABBIX_PROXY_SERVER:-"zabbix-server"}
  ZABBIX_PROXY_SERVER_PORT=${ZABBIX_PROXY_SERVER_PORT:-"10051"}
  ZABBIX_PROXY_LISTEN_PORT=${ZABBIX_PROXY_LISTEN_PORT:-"10051"}
  ZABBIX_PROXY_HOSTNAME=${ZABBIX_PROXY_HOSTNAME:-"zabbix-proxy"}
  ZABBIX_PROXY_ALLOW_ROOT=${ZABBIX_PROXY_ALLOW_ROOT:-"1"}
  ZABBIX_PROXY_USER=${ZABBIX_PROXY_USER:-"zabbix"}
  
### Debug Mode
  if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
    ZABBIX_PROXY_DEBUG_LEVEL=4
    set -x
  fi

### Check to see if Enabled/Disabled
  if [ "$ENABLE_ZABBIX" = "TRUE" ] || [ "$ENABLE_ZABBIX" = "true" ];  then
    sed -i -e "s|<ZABBIX_PROXY_LOGTYPE>|$ZABBIX_PROXY_LOGTYPE|g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s|<ZABBIX_PROXY_LOGFILE>|$ZABBIX_PROXY_LOGFILE|g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_LOGFILESIZE>/$ZABBIX_PROXY_LOGFILESIZE/g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_DEBUG_LEVEL>/$ZABBIX_PROXY_DEBUG_LEVEL/g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_MODE>/$ZABBIX_PROXY_MODE/g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_REMOTECOMMANDS>/$ZABBIX_PROXY_REMOTECOMMANDS/g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_REMOTECOMMANDS_LOG>/$ZABBIX_PROXY_REMOTECOMMANDS_LOG/g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s|<ZABBIX_PROXY_SERVER>|$ZABBIX_PROXY_SERVER|g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_LISTEN_PORT>/$ZABBIX_PROXY_LISTEN_PORT/g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_SERVER_PORT>/$ZABBIX_PROXY_SERVER_PORT/g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_HOSTNAME>/$ZABBIX_PROXY_HOSTNAME/g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_ALLOW_ROOT>/$ZABBIX_PROXY_ALLOW_ROOT/g" /etc/zabbix/zabbix_proxy.conf
    sed -i -e "s/<ZABBIX_PROXY_USER>/$ZABBIX_PROXY_USER/g" /etc/zabbix/zabbix_proxy.conf
  
    mkdir -p /var/log/zabbix
    chown -R $ZABBIX_PROXY_USER /var/log/zabbix
    chown -R $ZABBIX_PROXY_USER /etc/zabbix/

    if [ -d /assets/externalscripts ] ; then
       cp -R /assets/externalscripts/* /usr/lib/zabbix/externalscripts
       chown -R $ZABBIX_PROXY_USER /usr/lib/zabbix/externalscripts
       chmod -R 0755 /usr/lib/zabbix/externalscripts
    fi

    if [ -d /assets/alertscripts ] ; then
       cp -R /assets/alertscripts/* /usr/lib/zabbix/alertscripts
       chown -R $ZABBIX_PROXY_USER /usr/lib/zabbix/alertscripts
       chmod -R 0755 /usr/lib/zabbix/alertscripts
    fi

  else
    echo "**** [zabbix] Disabling Zabbix Proxy"
    s6-svc -d /var/run/s6/services/10-zabbix-proxy
  fi

  mkdir -p /tmp/state
  touch /tmp/state/10-zabbix-proxy-init
