#!/usr/bin/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/zabbix
source /assets/functions/30-zabbix

PROCESS_NAME="zabbix"

case "${ZABBIX_MODE}" in
    "PROXY" | "proxy" )
        print_debug "Zabbix Container Mode; Proxy"
        source /assets/defaults/zabbix-proxy
        service_stop 10-nginx
        service_stop 11-nginx-config-reload
        service_stop 20-php-fpm
        service_stop 30-zabbix-server
        service_stop 30-zabbix-webservice
        rm -rf /etc/logrotate.d/{nginx,php-fpm}
        configure_zabbix_proxy
        if [ "${ZABBIX_PROXY_LOG_TYPE}" = "FILE" ] || [ "${ZABBIX_PROXY_LOG_TYPE}" = "file" ] ; then
            create_logrotate zabbix_proxy ${ZABBIX_PROXY_LOG_PATH}/${ZABBIX_PROXY_LOG_FILE} ${ZABBIX_USER} ${ZABBIX_USER}
        fi
    ;;
    "SERVER" | "server" )
        print_debug "Zabbix Container Mode; Server"
        service_stop 10-nginx
        service_stop 11-nginx-config-reload
        service_stop 20-php-fpm
        service_stop 30-zabbix-proxy
        service_stop 30-zabbix-webservice
        rm -rf /etc/logrotate.d/{nginx,php-fpm}
        source /assets/defaults/zabbix-server
        sanity_db
        db_ready postgres
        db_bootstrap
        configure_zabbix_server
        if [ "${ZABBIX_SERVER_LOG_TYPE}" = "FILE" ] || [ "${ZABBIX_SERVER_LOG_TYPE}" = "file" ] ; then
            create_logrotate zabbix_server ${ZABBIX_SERVER_LOG_PATH}/${ZABBIX_SERVER_LOG_FILE} ${ZABBIX_USER} ${ZABBIX_USER}
        fi
    ;;
    "WEB" | "web" | "FRONTEND" | "frontend" )
        print_debug "Zabbix Container Mode; Web Frontend"
        check_service_initialized init 20-php-fpm
        sanity_db
        db_ready postgres
        service_stop 30-zabbix-proxy
        service_stop 30-zabbix-server
        service_stop 30-zabbix-webservice
        configure_zabbix_web_frontend
    ;;
    "WEBSERVICE" | "webservice" )
        print_debug "Zabbix Container Mode; Webservice"
        service_stop 10-nginx
        service_stop 11-nginx-config-reload
        service_stop 20-php-fpm
        service_stop 30-zabbix-proxy
        service_stop 30-zabbix-server
        rm -rf /etc/logrotate.d/{nginx,php-fpm}
        source /assets/defaults/zabbix-webservice
        configure_zabbix_webservice
        if [ "${ZABBIX_WEBSERVICE_LOG_TYPE}" = "FILE" ] || [ "${ZABBIX_WEBSERVICE_LOG_TYPE}" = "file" ] ; then
            create_logrotate zabbix_webservice ${ZABBIX_WEBSERVICE_LOG_PATH}/${ZABBIX_WEBSERVICE_LOG_FILE} ${ZABBIX_USER} ${ZABBIX_USER}
        fi
    ;;

    *)
        print_error "Unknown ZABBIX_MODE - exiting."
        exit 1
    ;;
esac

configure_alert_scripts
configure_external_scripts

liftoff