#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="zabbix-server"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting Zabbix Server"
exec s6-setuidgid zabbix zabbix_server -f;
