#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

### Start Zabbix
echo ''
echo '** [zabbix-frontend] Starting Zabbix Frontend'
touch /tmp/state/10-nginx
exec nginx;
