#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="zabbix-server"

set +e

# Script trace mode
if var_true "$DEBUG_MODE"; then
    set -o xtrace
fi

if [ ! -n "$zbx_type" ]; then
    print_error "Type of Zabbix component is not specified"
    exit 1
elif [ "$zbx_type" == "dev" ]; then
    print_notice "Deploying Zabbix installation from SVN"
else
    if [ ! -n "$zbx_db_type" ]; then
        print_error "Database type of Zabbix $zbx_type is not specified"
        exit 1
    fi

    if [ -n "$zbx_db_type" ]; then
        if [ -n "$zbx_opt_type" ]; then
            print_notice "Deploying Zabbix $zbx_type ($zbx_opt_type) with $zbx_db_type database"
        else
            print_notice "Deploying Zabbix $zbx_type with $zbx_db_type database"
        fi
    else
        print_notice "Deploying Zabbix $zbx_type"
    fi
fi

prepare_system "$zbx_type" "$zbx_opt_type"

[ "$zbx_type" == "server" ] && prepare_server "$zbx_db_type"
[ "${ZBX_ADD_SERVER}" == "true" ] && prepare_server "${ZBX_MAIN_DB}"

[ "$zbx_type" == "java-gateway" ] && prepare_java_gateway
[ "${ZBX_ADD_JAVA_GATEWAY}" == "true" ] && prepare_java_gateway

clear_deploy "$zbx_type"

if [ -d /assets/externalscripts ]; then
    mkdir -p /usr/lib/zabbix/externalscripts
    cp -R /assets/externalscripts/* /usr/lib/zabbix/externalscripts
    chown -R "$ZABBIX_USER" /usr/lib/zabbix/externalscripts
    chmod -R 0755 /usr/lib/zabbix/externalscripts
fi

if [ -d /assets/alertscripts ]; then
    mkdir -p /usr/lib/zabbix/alertscripts
    cp -R /assets/alertscripts/* /usr/lib/zabbix/alertscripts
    chown -R "$ZABBIX_USER" /usr/lib/zabbix/alertscripts
    chmod -R 0755 /usr/lib/zabbix/alertscripts
fi

liftoff
