#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/zabbix
source /assets/defaults/zabbix-webservice
SERVICE_NAME="zabbix-webservice"

check_container_initialized
liftoff

print_start "Starting Zabbix Web Service ${ZABBIX_VERSION}"
silent exec s6-setuidgid ${ZABBIX_USER} zabbix_web_service -c "${ZABBIX_WEBSERVICE_CONFIG_PATH}"/"${ZABBIX_WEBSERVICE_CONFIG_FILE}"
