version: '3.7'
services:

  zabbix-domain-org-app:
    image: tiredofit/zabbix-frontend:latest
    container_name: zabbix-domain-org-app
    links:
    - zabbix-domain-org-db
    - zabbix-domain-org-server
    mem_limit: 512m
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:zabbix.example.com
    - traefik.port=80
    - traefik.protocol=http
    - traefik.docker.network=proxy
    - traefik.backend=zabbix-domain-org-app
    environment:
    - VIRTUAL_HOST=zabbix.example.com
    - VIRTUAL_NETWORK=proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=zabbix.example.com
    - LETSENCRYPT_EMAIL=techsupport@example.com

    - ZABBIX_SERVER_ACTIVE=zabbix-domain-org-server
    - ZABBIX_SERVER_PORT=10051
    - ZABBIX_SERVER_NAME=zabbix.example.com

    - DB_HOST=zabbix-domain-org-db
    - DB_TYPE=POSTGRESQL
    - DB_PORT=5432
    - DB_USER=zabbix
    - DB_PASS=password
    - DB_NAME=zabbix
    - DB_SCHEMA=public
    networks:
    - proxy
    - internal
    - services
    zbx_net:
    aliases:
    - zabbix-web-nginx-pgsql
    - zabbix-web-nginx-alpine-pgsql
    - zabbix-web-nginx-pgsql-alpine
    restart: always

networks:
  proxy:
    external: true
  internal:
    external: false
  services:
    external: true
  zbx_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
