#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/zabbix
source /assets/defaults/zabbix-proxy
PROCESS_NAME="zabbix-proxy"

check_container_initialized
liftoff

print_start "Starting Zabbix Proxy ${ZABBIX_VERSION}"
silent s6-setuidgid ${ZABBIX_USER} zabbix_proxy -c "${ZABBIX_PROXY_CONFIG_PATH}"/"${ZABBIX_PROXY_CONFIG_FILE}" -f;
