#!/usr/bin/with-contenv bash

### Set Defaults
  PHP_TIMEOUT=${PHP_TIMEOUT:-"600"}
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:-"2G"}
  

### Adjust NGINX Runtime Variables  
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
  sed -i -e "s/<PHP_TIMEOUT>/$PHP_TIMEOUT/g" /etc/nginx/conf.d/default.conf

### Sanity Test
if [ ! -n "DB_TYPE" ]; then
    echo '** [zabbix-frontend] ERROR: No Database Host Entered! '
    exit 1
fi

if [ ! -n "DB_HOST" ]; then
    echo '** [zabbix-frontend] ERROR: No Database Host Entered! '
    exit 1
fi

if [ ! -n "DB_NAME" ]; then
    echo '** [zabbix-frontend] ERROR: No Database Pass Entered! '
    exit 1
fi

if [ ! -n "DB_SCHEMA" ]; then
    echo '** [zabbix-frontend] ERROR: No Database Host Entered! '
    exit 1
fi

if [ ! -n "DB_USER" ]; then
    echo '** [zabbix-frontend] ERROR: No Database User Entered! '
    exit 1
fi

if [ ! -n "DB_PASS" ]; then
    echo '** [zabbix-frontend] ERROR: No Database Pass Entered! '
    exit 1
fi

if [ ! -n "DB_PORT" ]; then
    echo '** [zabbix-frontend] ERROR: No Database Host Entered! '
    exit 1
fi

cat <<EOF > /usr/share/webapps/zabbix/conf/zabbix.conf.php
<?php
// Zabbix GUI configuration file.
global \$DB;

\$DB['TYPE']		= '$DB_TYPE';
\$DB['SERVER']		= '$DB_HOST';
\$DB['PORT']		= '$DB_PORT';
\$DB['DATABASE']	= '$DB_NAME';
\$DB['USER']		= '$DB_USER';
\$DB['PASSWORD']	= '$DB_PASS';
\$DB['SCHEMA']		= '$DB_SCHEMA';

\$ZBX_SERVER   		= '$ZABBIX_SERVER_ACTIVE';
\$ZBX_SERVER_PORT 	= '$ZABBIX_SERVER_PORT';
\$ZBX_SERVER_NAME 	= '$ZABBIX_SERVER_NAME';

\$IMAGE_FORMAT_DEFAULT	= IMAGE_FORMAT_PNG;
EOF

if [ ! -f /www/html/index.php ] ; then
	mkdir -p www
	ln -s /usr/share/webapps/zabbix /www/html
fi

### Force Reset Permissions for Security
chown -R nginx:www-data /usr/share/webapps/zabbix/
mkdir -p /www/logs/nginx
mkdir -p /tmp/nginx
chown -R nginx /www/logs/nginx
chown nginx /tmp/nginx
